version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: stream_pulse_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: streampulse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d streampulse"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stream_pulse_network

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: stream_pulse_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - stream_pulse_network

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    hostname: openldap  # Explicitly set hostname
    environment:
      - LDAP_ORGANISATION=Dev-Lab
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_TLS=false
    ports:
      - "389:389"
    networks:
      - stream_pulse_network

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
      # Skip trying to use the 'example.com' default
      - PHPLDAPADMIN_SERVER_ADMIN_RESPONDER=admin@example.org 
    ports:
      - "8081:80"
    depends_on:
      - openldap
    networks:
      - stream_pulse_network

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  stream_pulse_network:
    driver: bridge
